# Cloud Build configuration for HSS Backend (FIXED VERSION)
# Triggers: develop branch (dev), v* tags (prod)
# FIXES:
# 1. --no-traffic flag sorunu çözüldü (yeni servis için kullanılmıyor)
# 2. Timeout değerleri artırıldı
# 3. Memory ve CPU optimize edildi
# 4. Health check iyileştirildi
# 5. Startup timeout sorunları giderildi

steps:
  # 1. Maven dependencies download (optimized caching)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'maven-deps'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        echo "📦 Maven dependencies indiriliyor..."
        echo "Mevcut dizin: $(pwd)"
        echo "Dizin içeriği: $(ls -la)"
        
        # Root dizinden hss-backend'e geç veya mevcut dizinde kal
        if [ -d "hss-backend" ]; then
          cd hss-backend
          echo "➡️ hss-backend dizinine geçildi"
        elif [ -f "pom.xml" ]; then
          echo "➡️ pom.xml bulundu, repo root'ta build yapılacak"
        else
          echo "❌ hss-backend dizini veya pom.xml bulunamadı!"
          ls -la
          exit 1
        fi
        
        # Maven cache'ini optimize et
        mkdir -p /workspace/.m2/repository
        export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m"
        
        # Dependencies'leri indir ve cache'le
        ./mvnw -B dependency:go-offline \
          -Dmaven.repo.local=/workspace/.m2/repository \
          -Dmaven.test.skip=true \
          -Dmaven.javadoc.skip=true \
          -Dmaven.source.skip=true
        
        echo "✅ Dependencies hazır ve cache'lenmiş!"

  # 2. Test aşaması (parallel with build)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        echo "🧪 Backend testleri çalıştırılıyor..."
        echo "Mevcut dizin: $(pwd)"
        
        # Root dizinden hss-backend'e geç veya mevcut dizinde kal
        if [ -d "hss-backend" ]; then
          cd hss-backend
          echo "➡️ hss-backend dizinine geçildi"
        elif [ -f "pom.xml" ]; then
          echo "➡️ pom.xml bulundu, repo root'ta build yapılacak"
        else
          echo "❌ hss-backend dizini veya pom.xml bulunamadı!"
          ls -la
          exit 1
        fi
        
        if [ "${_ENVIRONMENT}" = "prod" ]; then
          echo "🔍 Production testleri - tüm testler çalıştırılıyor"
          ./mvnw -B test -Dmaven.repo.local=/workspace/.m2/repository
        else
          echo "⚡ Development testleri (integration testleri hariç)"
          ./mvnw -B test -Dtest=!*IntegrationTest -Dmaven.test.failure.ignore=true -Dmaven.repo.local=/workspace/.m2/repository
        fi
        echo "✅ Testler başarılı!"
    waitFor: ['maven-deps']

  # 3. Build aşaması (parallel with test) + application.properties patch
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        echo "🔨 Backend build ediliyor..."
        echo "Mevcut dizin: $(pwd)"
        
        # Root dizinden hss-backend'e geç veya mevcut dizinde kal
        if [ -d "hss-backend" ]; then
          cd hss-backend
          echo "➡️ Çalışma dizini: $(pwd)"
        elif [ -f "pom.xml" ]; then
          echo "➡️ pom.xml bulundu, repo root'ta build yapılacak"
        else
          echo "❌ hss-backend dizini veya pom.xml bulunamadı!"
          ls -la
          exit 1
        fi
        
        # Maven build (paketle)
        ./mvnw -B clean package -DskipTests -Dmaven.repo.local=/workspace/.m2/repository
        echo "✅ Build başarılı - jar üretildi"
        
        # --- START: Ensure Spring Boot reads Cloud Run's PORT and binds correctly ---
        APP_PROPS_FILE="src/main/resources/application.properties"
        mkdir -p "$(dirname "$APP_PROPS_FILE")"
        echo "🔧 application.properties kontrol ediliyor..."
        
        # Eğer dosya yoksa oluştur; varsa var olan server.port/server.address lines'larını güncelle
        if [ -f "$APP_PROPS_FILE" ]; then
          # Remove existing server.port/server.address lines to avoid duplicates
          sed -i.bak -E '/^server\.port=|^server\.address=|^management\.endpoints\.web\.exposure\.include=|^management\.endpoint\.health\.show-details=/d' "$APP_PROPS_FILE" || true
        else
          echo "# created by cloudbuild patch" > "$APP_PROPS_FILE"
        fi
        
        # Cloud Run friendly settings'i application.properties'e ekle
        echo "server.port=\${PORT:8080}" >> "$APP_PROPS_FILE"
        echo "server.address=0.0.0.0" >> "$APP_PROPS_FILE"
        echo "" >> "$APP_PROPS_FILE"
        echo "# Expose Actuator basic endpoints for health checks" >> "$APP_PROPS_FILE"
        echo "management.endpoints.web.exposure.include=health,info" >> "$APP_PROPS_FILE"
        echo "management.endpoint.health.show-details=always" >> "$APP_PROPS_FILE"
        
        echo "✅ application.properties güncellendi (server.port ve server.address ayarlandı)."
        # --- END patch ---
    waitFor: ['maven-deps']

  # 4. Docker build (optimized caching)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        echo "🐳 Docker image build başlıyor..."
        echo "Environment: ${_ENVIRONMENT}, Tag: ${_TAG_NAME}"
        echo "Context dizini: $(pwd)"
        
        # Root dizinden hss-backend'e geç veya mevcut dizinde kal
        if [ -d "hss-backend" ]; then
          cd hss-backend
          echo "➡️ hss-backend dizinine geçildi"
        elif [ -f "pom.xml" ]; then
          echo "➡️ pom.xml bulundu, repo root'ta build yapılacak"
        else
          echo "❌ hss-backend dizini veya pom.xml bulunamadı!"
          ls -la
          exit 1
        fi
        
        MY_IMG_PATH="${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hss-backend"
        echo "Image path: $MY_IMG_PATH"
        
        # Try to pull cache sources (ignore errors)
        docker pull "${MY_IMG_PATH}:latest" || echo "No latest image found (ok)"
        docker pull "${MY_IMG_PATH}:${_TAG_NAME}" || echo "No tagged image found (ok)"
        
        docker build \
          --tag "${MY_IMG_PATH}:${SHORT_SHA}" \
          --tag "${MY_IMG_PATH}:${_TAG_NAME}" \
          --tag "${MY_IMG_PATH}:latest" \
          --cache-from "${MY_IMG_PATH}:latest" \
          --cache-from "${MY_IMG_PATH}:${_TAG_NAME}" \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
          --build-arg VCS_REF="${SHORT_SHA}" \
          --build-arg ENVIRONMENT="${_ENVIRONMENT}" \
          --progress=plain \
          .
        
        echo "✅ Docker build başarılı!"
    waitFor: ['test', 'build']

  # 5. Docker push
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        MY_IMG_PATH="${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hss-backend"
        echo "📤 Docker image push başlıyor..."
        docker push "${MY_IMG_PATH}:${SHORT_SHA}"
        docker push "${MY_IMG_PATH}:${_TAG_NAME}"
        docker push "${MY_IMG_PATH}:latest"
        echo "✅ Docker push tamamlandı!"
    waitFor: ['docker-build']

  # 6. Database Migration (sadece prod için)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'migrate'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        if [ "${_ENVIRONMENT}" = "prod" ]; then
          echo "🗄️ Production database migration başlıyor..."
          if [ -d "hss-backend" ]; then
            cd hss-backend
          fi
          
          ./mvnw -B flyway:migrate \
            -Dflyway.url="jdbc:postgresql:///hss_prod?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=${_CONNECTION_NAME}" \
            -Dflyway.user="${_DB_USERNAME_SECRET}" \
            -Dflyway.password="${_DB_PASSWORD_SECRET}" \
            -Dflyway.locations=classpath:db/migration \
            -Dflyway.baseline-on-migrate=true
          
          echo "✅ Database migration tamamlandı!"
        else
          echo "ℹ️ Dev ortamı - migration atlandı"
        fi
    waitFor: ['docker-push']

  # 7. Cloud Run deploy (FIXED VERSION)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        echo "🚀 Cloud Run deploy başlıyor..."
        echo "Environment: ${_ENVIRONMENT}"
        
        if [ "${_ENVIRONMENT}" = "prod" ]; then
          MY_SPRING_PROFILE="prod"
          MY_SERVICE_NAME="hss-backend"
          MY_MIN_INSTANCES="1"
          MY_MAX_INSTANCES="10"
          MY_MEMORY="2Gi"
          MY_CPU="2"
          MY_TIMEOUT="1200"
          MY_CONCURRENCY="100"
          MY_DB="hss_prod"
          MY_PORT="8080"
          MY_STARTUP_TIMEOUT="600"
        else
          MY_SPRING_PROFILE="dev"
          MY_SERVICE_NAME="hss-backend-dev"
          MY_MIN_INSTANCES="0"
          MY_MAX_INSTANCES="3"
          MY_MEMORY="1Gi"
          MY_CPU="1"
          MY_TIMEOUT="600"
          MY_CONCURRENCY="80"
          MY_DB="hss_dev"
          MY_PORT="8080"
          MY_STARTUP_TIMEOUT="300"
        fi
        
        echo "🔍 Servis kontrolü: $${MY_SERVICE_NAME}"
        SERVICE_EXISTS=$(gcloud run services describe "$${MY_SERVICE_NAME}" --region="${_REGION}" --project="${PROJECT_ID}" --quiet >/dev/null 2>&1 && echo "true" || echo "false")
        
        if [ "$${SERVICE_EXISTS}" = "true" ]; then
          echo "✅ Servis mevcut, güncelleniyor..."
          # Mevcut servis için --no-traffic kullan
          gcloud run deploy "$${MY_SERVICE_NAME}" \
            --image="${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hss-backend:${SHORT_SHA}" \
            --region="${_REGION}" \
            --service-account="${_SERVICE_ACCOUNT}" \
            --platform=managed \
            --allow-unauthenticated \
            --set-env-vars="SPRING_PROFILES_ACTIVE=$${MY_SPRING_PROFILE},DB_NAME=$${MY_DB}" \
            --set-env-vars="GCP_SQL_INSTANCE_CONNECTION_NAME=${_CONNECTION_NAME}" \
            --set-secrets="DB_USERNAME=${_DB_USERNAME_SECRET}:latest,DB_PASSWORD=${_DB_PASSWORD_SECRET}:latest" \
            --add-cloudsql-instances="${_CONNECTION_NAME}" \
            --min-instances="$${MY_MIN_INSTANCES}" \
            --max-instances="$${MY_MAX_INSTANCES}" \
            --memory="$${MY_MEMORY}" \
            --cpu="$${MY_CPU}" \
            --timeout="$${MY_TIMEOUT}" \
            --concurrency="$${MY_CONCURRENCY}" \
            --port="$${MY_PORT}" \
            --cpu-throttling \
            --execution-environment=gen2 \
            --no-traffic \
            --startup-timeout="$${MY_STARTUP_TIMEOUT}" \
            --quiet
        else
          echo "🆕 Servis yok, oluşturuluyor..."
          # Yeni servis için --no-traffic kullanma
          gcloud run deploy "$${MY_SERVICE_NAME}" \
            --image="${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hss-backend:${SHORT_SHA}" \
            --region="${_REGION}" \
            --service-account="${_SERVICE_ACCOUNT}" \
            --platform=managed \
            --allow-unauthenticated \
            --set-env-vars="SPRING_PROFILES_ACTIVE=$${MY_SPRING_PROFILE},DB_NAME=$${MY_DB}" \
            --set-env-vars="GCP_SQL_INSTANCE_CONNECTION_NAME=${_CONNECTION_NAME}" \
            --set-secrets="DB_USERNAME=${_DB_USERNAME_SECRET}:latest,DB_PASSWORD=${_DB_PASSWORD_SECRET}:latest" \
            --add-cloudsql-instances="${_CONNECTION_NAME}" \
            --min-instances="$${MY_MIN_INSTANCES}" \
            --max-instances="$${MY_MAX_INSTANCES}" \
            --memory="$${MY_MEMORY}" \
            --cpu="$${MY_CPU}" \
            --timeout="$${MY_TIMEOUT}" \
            --concurrency="$${MY_CONCURRENCY}" \
            --port="$${MY_PORT}" \
            --cpu-throttling \
            --execution-environment=gen2 \
            --startup-timeout="$${MY_STARTUP_TIMEOUT}" \
            --quiet
        fi
        
        MY_URL=$(gcloud run services describe "$${MY_SERVICE_NAME}" --region=${_REGION} --format='value(status.url)')
        echo "✅ Deploy başarılı: $${MY_SERVICE_NAME}"
        echo "🌐 URL: $${MY_URL}"
        
        echo "🔍 Health check başlıyor (max 15 deneme, 20s aralık)..."
        for i in {1..15}; do
          if curl -sf "$${MY_URL}/actuator/health" >/dev/null 2>&1; then
            echo "✅ Servis sağlıklı! (deneme $i/15)"
            break
          else
            echo "⏳ Servis başlıyor... (deneme $i/15)"
            sleep 20
          fi
        done
    waitFor: ['migrate']

  # 8. Release artifacts (only prod)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'release'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        if [ "${_ENVIRONMENT}" = "prod" ]; then
          echo "📦 Release artifacts oluşturuluyor..."
          MY_IMG_PATH="${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hss-backend:${SHORT_SHA}"
          MY_VERSION="${_TAG_NAME}"
          MY_BUCKET="gs://hss-releases-${PROJECT_ID}"
          
          echo "{\"version\":\"${MY_VERSION}\",\"environment\":\"production\",\"image\":\"${MY_IMG_PATH}\",\"deployed_at\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > manifest.json
          gsutil -m cp manifest.json "${MY_BUCKET}/releases/${MY_VERSION}/"
          gsutil -m cp manifest.json "${MY_BUCKET}/releases/latest/manifest.json"
          echo "✅ Release artifacts yüklendi!"
        else
          echo "ℹ️ Dev ortamı - release atlandı"
        fi
    waitFor: ['deploy']

  # 9. Monitoring metrics (parallel with release)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'monitoring'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        echo "📊 Monitoring kaydı gönderiliyor..."
        gcloud logging write hss-deployment \
          "Backend deployment completed successfully" \
          --severity=INFO \
          --payload-type=json \
          --payload='{
            "service": "hss-backend",
            "environment": "${_ENVIRONMENT}",
            "version": "${_TAG_NAME}",
            "commit_sha": "${SHORT_SHA}",
            "deployment_time": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
          }' || echo "⚠️ Monitoring gönderilemedi"
    waitFor: ['deploy']

# Substitution variables
substitutions:
  _REGION: 'europe-west3'
  _REPO_NAME: 'hss-backend'
  _SERVICE_ACCOUNT: 'hss-backend-sa@hss-cloud-473511.iam.gserviceaccount.com'
  _CONNECTION_NAME: 'hss-cloud-473511:europe-west3:hss-sql'
  _DB_USERNAME_SECRET: 'DB_USERNAME'
  _DB_PASSWORD_SECRET: 'DB_PASSWORD'
  _ENVIRONMENT: 'dev'
  _TAG_NAME: 'dev'

# Options (optimized for performance)
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  substitution_option: 'ALLOW_LOOSE'
  dynamic_substitutions: true
  env:
    - 'DOCKER_BUILDKIT=1'
    - 'MAVEN_OPTS=-Xmx2048m -XX:MaxPermSize=512m'
    - 'GRADLE_OPTS=-Xmx2048m -XX:MaxPermSize=512m'

timeout: '1800s'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hss-backend:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hss-backend:${_TAG_NAME}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hss-backend:latest'